In [62]:
import torch

In [64]:
x=torch.randn(3, requires_grad=True)
print(x)

tensor([-2.3064, -1.4794, -1.1531], requires_grad=True)


In [66]:
y=x+2

In [68]:
print(y)

tensor([-0.3064,  0.5206,  0.8469], grad_fn=<AddBackward0>)


In [70]:
z=y*y*2
print(z)
print(z.mean())

tensor([0.1877, 0.5420, 1.4345], grad_fn=<MulBackward0>)
tensor(0.7214, grad_fn=<MeanBackward0>)


In [71]:
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([-0.1226,  2.0824,  0.0034])


In [80]:
weights=torch.ones(4,requires_grad=True)

for epoch in range(2):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
