In [50]:
import torch
import numpy as np

In [16]:
x=torch.ones(2,3,dtype=torch.float16)
print(x.dtype)

torch.float16


In [18]:
print(x.size())

torch.Size([2, 3])


In [22]:
y=torch.tensor([2,5])
print(y.size())

torch.Size([2])


In [25]:
a=torch.rand(2,2)
b=torch.rand(2,2)
a,b

(tensor([[0.8891, 0.1668],
         [0.0018, 0.3829]]),
 tensor([[0.9489, 0.0125],
         [0.3266, 0.7682]]))

In [29]:
c=a*b
print(c)
print(torch.add(a,b))

tensor([[8.4365e-01, 2.0779e-03],
        [5.8546e-04, 2.9412e-01]])
tensor([[1.8380, 0.1792],
        [0.3284, 1.1511]])


In [31]:
b.add_(a)
print(b)

tensor([[2.7271, 0.3460],
        [0.3302, 1.5339]])


In [63]:
#slicing
d=torch.rand(5,3)
print(d)
print(d[1,1].item())
print(d[1,1])#We can use item if we have only one element in the tensor|

tensor([[0.9853, 0.8916, 0.7469],
        [0.2188, 0.2966, 0.7815],
        [0.9652, 0.0099, 0.0124],
        [0.6840, 0.8092, 0.1567],
        [0.3519, 0.1076, 0.8393]])
0.2966281771659851
tensor(0.2966)


In [41]:
zw=torch.rand(4,4)
print(zw)

tensor([[0.6872, 0.4537, 0.9209, 0.0231],
        [0.4164, 0.0021, 0.7990, 0.2603],
        [0.2680, 0.7009, 0.2020, 0.4758],
        [0.8761, 0.1809, 0.0221, 0.6623]])


In [51]:
za=zw.view(-1,8)
print(za)

tensor([[0.6872, 0.4537, 0.9209, 0.0231, 0.4164, 0.0021, 0.7990, 0.2603],
        [0.2680, 0.7009, 0.2020, 0.4758, 0.8761, 0.1809, 0.0221, 0.6623]])


In [53]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [57]:
b=a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [61]:
aa=np.ones(5)
print(aa)
bb=torch.from_numpy(aa)
print(bb)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [66]:
#Numpy can only handle cpu tensors
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.ones(5,device=device)
    y=torch.ones(5)
    y=y.to(device)#loading on gpu
    z=x+y
    z=z.to("cpu")#back t